[build]
command = "npm install && npm run build"
publish = "dist"
functions = "api"

[[redirects]]
from = "/clip"
to = "/.netlify/functions/clip"
status = 200
  [query]
  v = ":videoId"
  r = ":range"
  t = ":title"
  d = ":description"