[build]
command = "npm install && npm run build"
publish = "dist"
functions = "api"

[[redirects]]
from = "/clip v=:videoId r=:range t=:title d=:description"
to = "/.netlify/functions/clip"
status = 200